the_poll_kokoc/polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('take_poll/<int:poll_id>/', views.take_poll, name='take_poll'),
    path('shop/', views.shop, name='shop'),
    path('profile/', views.profile, name='profile'),
    path('userboard/', views.userboard, name='userboard')
]

the_poll_kokoc/the_poll_kokoc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls', namespace='polls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls'),)
]

the_poll_kokoc/templates/includes/footer.html
<footer class="border-top text-center py-3">
  2022   
</footer>

the_poll_kokoc/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container">
      <ul class="nav nav-pills nav-fill w-100">
        {% with request.resolver_match.view_name as view_name %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'polls:index' %}active{% endif %}" 
            href="{% url 'polls:index' %}">Главная</a>
          </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'polls:userboard' %}active{% endif %}"
            href="{% url 'polls:userboard' %}">Список пользователей</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'polls:profile' %}active{% endif %}" 
            href="{% url 'polls:profile' %}">Профиль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'polls:shop' %}active{% endif %}" 
            href="{% url 'polls:shop' %}">Магазин</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'users:password_change' %}active{% endif %}" 
            href="{% url 'users:password_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'users:logout' %}active{% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link" 
            href="{% url 'polls:profile' %}"> {{ user.username }} </a>
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'users:login' %}active{% endif %}"
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link {% if view_name == 'users:signup' %}active{% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

the_poll_kokoc/templates/includes/poll_card.html
<div class="card-body border border-primary rounded">
  <h3>{{ poll.name }}</h3>
  <p>
    {{ poll.description }}
  </p>
  <p>
    Награда за прохождение: {{ poll.reward }}
  </p>
  {% if user.is_authenticated %}
    <a href="{% url 'polls:take_poll' poll.id %}"> Пройти опрос </a>
  {% endif %}
</div>

the_poll_kokoc/templates/includes/question_card.html
<form method="post">
  {% csrf_token %}
  {{ formset.management_form }}
  <table>
    {% for form, question in question_data %}
      <div class="card-body">
        <h3> {{ question.text }} </h3>
        {% for field in form %}
          {{ field }}
        {% endfor %}
        {% if form.errors %}
          {% for field in form %} 
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
      </div>
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </table>
<button type="submit" class="btn btn-primary">
  Ответить
</button>
</form>

the_poll_kokoc/templates/includes/user_card.html
<div class="card-body bg-{{ user.background_color.color }} rounded">
  <div class="mb-1 border border-3 border-{{ user.login_color.color }}">
    <h3>{{ user.get_username }}</h3>
  </div>
  <p>
    Пройдено тестов: {{ tests_done }}
  </p>
</div>